services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql 
  lingblog:
    image: node:latest
    command: node /www/server/index.mjs
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    volumes:
      - ./.output:/www
    ports:
      - "80:3000"
    depends_on:
      - postgres